version: "3.8"

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx_proxy
    labels:
      com.github.nginx-proxy.nginx-proxy: "true"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs:ro
      - ./vhost.d:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
      - ./nginx/certs:/etc/nginx/certs
      # - ./nginx/conf.d:/etc/nginx/conf.d # Commented due to use nginx-proxy-letsencrypt
    networks:
      - wpnet

  letsencrypt:
    image: nginxproxy/acme-companion
    container_name: nginx_proxy_letsencrypt
    environment:
      DEFAULT_EMAIL: ${EMAIL}
      NGINX_PROXY_CONTAINER: nginx_proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs:/etc/nginx/certs
      - ./vhost.d:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
    depends_on:
      - nginx-proxy
    networks:
      - wpnet

  wordpress:
    container_name: wordpress_app
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "9000"
    environment:
      - VIRTUAL_HOST=${WORDPRESS_DOMAIN}
      - LETSENCRYPT_HOST=${WORDPRESS_DOMAIN}
      - LETSENCRYPT_EMAIL=${EMAIL}
    volumes:
      - ./wordpress:/var/www/html:cached
      - ./php-logs:/var/log/php
    depends_on:
      - db
    networks:
      - wpnet

  db:
    container_name: wordpress_db
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER:-wpuser}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-wppassword}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - wpnet

  phpmyadmin:
    container_name: wordpress_phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: ${MYSQL_DB_HOST:-db}
      PMA_USER: ${PMA_USER:-wpuser}
      PMA_PASSWORD: ${PMA_PASSWORD:-wppassword}
      VIRTUAL_HOST: ${PMA_DOMAIN}
      LETSENCRYPT_HOST: ${PMA_DOMAIN}
      LETSENCRYPT_EMAIL: ${EMAIL}
    networks:
      - wpnet
    depends_on:
      - db

volumes:
  db_data:

networks:
  wpnet:
