version: "3.8"

services:
  wordpress:
    container_name: wordpress_app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./wordpress:/var/www/html:cached
      - ./php-logs:/var/log/php
    depends_on:
      - db
    networks:
      - wpnet

  nginx:
    container_name: wordpress_nginx
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - ./wordpress:/var/www/html:cached
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - wordpress
    networks:
      - wpnet

  db:
    container_name: wordpress_db
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: wppassword
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - wpnet

  phpmyadmin:
    container_name: wordpress_phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: wpuser
      PMA_PASSWORD: wppassword
    ports:
      - "8080:80"
    networks:
      - wpnet
    depends_on:
      - db

volumes:
  db_data:

networks:
  wpnet:
